version: '3.8'

services:
  client:
    container_name: todo-client
    image: todo-client:0.0.1
    build:
      context: ./todo-client
    ports:
      - "5173:80"
    depends_on:
      - server
  server:
    container_name: todo-server
    image: todo-server:0.0.1
    build:
      context: ./todo-server
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_NAME: todo
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: todo_db
    depends_on:
      - todo_db
  todo_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: {}
